
@token = vk1.a.RRNfyTIHfp3y5r3kPa3nD3q8aBTTG81zqLCFA0iKElT27FwkAzIRU2jadBT5woCCIWH0Y8-zL-uvTZUXU3Uo45hq6dwpLZ7ZHUMwvOArzsPvzZmPpkPs8a8O3Hukc7KgvjIec6AVN2xZxP3JuYJtVShUgh24l_ntYpbj-B9DfXN2C7aUJOBKDtzmhXqsE0hfn-ahk2FElfLiV2z1Ul9dqw
@v = 5.131
@owner_id=703758419

@album_id = profile
GET https://api.vk.com/method/photos.get?access_token={{token}}&v={{v}}&owner_id=703758419&album_id=profile
